services:
  app:
    image: golang:1.22.3
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mercarius_db
      MYSQL_USER: mercarius
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
