services:
  app:
    image: golang:1.22.3
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mercarius_db
      - DSN=root:password@tcp(mysql:3306)/
      - DSN_PARAM=?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci
      - API_KEY=${API_KEY}
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mercarius_db
      MYSQL_USER: mercarius
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
